env = Environment(CPPPATH='include')
#env.Tool('crossmingw', toolpath = ['scons-tools'])
Export("env")
#bases = SConscript("cffi/objectmodels/SConscript")
#expat = SConscript("extern/expat/SConscript")
#libffi = env.Library("cffi", [bases])
#env.Program("test.cpp", LIBS=["cffi"], LIBPATH=['.'])
#env.Program(["test.cpp"] + bases)
env.Program(["test/object_models/object_test.cpp"], LIBS=["boost_unit_test_framework"])
env.Program(["oldtest.cpp"])
